# Generated by Django 4.2.6 on 2024-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_trainer_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(blank=True, choices=[('weight', 'Weight loss'), ('muscle', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('other', 'Other')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_type',
            field=models.CharField(blank=True, choices=[('trainer', 'Trainer'), ('nutritionist', 'Nutritionist'), ('both', 'Trainer and Nutritionist')], max_length=12, null=True),
        ),
    ]
