# Generated by Django 4.2.6 on 2024-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_regularuser_arm_regularuser_chest_regularuser_glute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
