# Generated by Django 4.2.6 on 2024-01-23 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_trainer_specialty_trainer_trainer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('weight', 'Weight loss'), ('muscle', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('other', 'Other')], max_length=11), blank=True, null=True, size=None),
        ),
    ]
