# Generated by Django 4.2.6 on 2024-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_trainer_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('weight', 'Weight loss'), ('muscle', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialty',
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='user.specialty'),
        ),
    ]
