# Generated by Django 4.2.6 on 2024-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_trainingrequest_description_trainingrequest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='communication_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
