# Generated by Django 4.2.6 on 2024-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_specialty_remove_trainer_specialty_trainer_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='specialty',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
