# Generated by Django 4.2.6 on 2024-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_regularuser_communication_email_regularuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='communication_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
