# Generated by Django 4.2.6 on 2024-01-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_trainer_specialty_delete_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialty',
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialties', to='user.specialty'),
        ),
    ]
