# Generated by Django 4.2.6 on 2024-06-12 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_trainer_communication_email_trainer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUserMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('shoulder', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hip', models.FloatField(blank=True, null=True)),
                ('arm', models.FloatField(blank=True, null=True)),
                ('glute', models.FloatField(blank=True, null=True)),
                ('upper_leg', models.FloatField(blank=True, null=True)),
                ('middle_leg', models.FloatField(blank=True, null=True)),
                ('lower_leg', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
