# Generated by Django 4.2.6 on 2024-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_specialty_remove_trainer_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(choices=[('weight_loss', 'Weight loss'), ('muscle_gain', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('other', 'Other')], max_length=100, unique=True),
        ),
    ]
