# Generated by Django 4.2.6 on 2024-01-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_specialty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('regular_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer')),
            ],
            options={
                'unique_together': {('regular_user', 'trainer')},
            },
        ),
    ]
