# Generated by Django 4.2.6 on 2024-01-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_trainingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='personal_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.trainer'),
        ),
    ]
