# Generated by Django 4.2.6 on 2024-01-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_regularuser_personal_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='user.regularuser'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='user.specialty'),
        ),
    ]
