# Generated by Django 4.2.6 on 2024-01-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_alter_trainer_clients_alter_trainer_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('saturated_fat', models.FloatField(default=0)),
                ('gluten_free', models.BooleanField(default=False)),
                ('lactose_free', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('pescetarian', models.BooleanField(default=False)),
                ('contains_meat', models.BooleanField(default=False)),
                ('contains_vegetables', models.BooleanField(default=False)),
                ('contains_fish_shellfish', models.BooleanField(default=False)),
                ('canned_or_preserved', models.BooleanField(default=False)),
                ('cereal', models.BooleanField(default=False)),
                ('pasta_or_rice', models.BooleanField(default=False)),
                ('dairy_yogurt_cheese', models.BooleanField(default=False)),
                ('fruit', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('legume', models.BooleanField(default=False)),
                ('sauce_or_condiment', models.BooleanField(default=False)),
                ('deli_meat', models.BooleanField(default=False)),
                ('bread_or_toast', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('special_drink_or_supplement', models.BooleanField(default=False)),
                ('tuber', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('dishes', models.ManyToManyField(to='nutrition.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='g', max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.diet')),
                ('meals', models.ManyToManyField(to='nutrition.meal')),
            ],
            options={
                'unique_together': {('diet', 'date')},
            },
        ),
    ]
