# Generated by Django 4.2.6 on 2024-02-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.dish'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='nutrition.DishIngredient', to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='dailydiet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.diet'),
        ),
        migrations.AddField(
            model_name='dailydiet',
            name='meals',
            field=models.ManyToManyField(to='nutrition.meal'),
        ),
        migrations.AlterUniqueTogether(
            name='mealdish',
            unique_together={('meal', 'dish')},
        ),
        migrations.AlterUniqueTogether(
            name='dailydiet',
            unique_together={('diet', 'date')},
        ),
    ]
