# Generated by Django 3.2.1 on 2024-02-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='canned_or_preserved',
            new_name='contains_fish_shellfish_canned_preserved',
        ),
        migrations.RemoveField(
            model_name='food',
            name='contains_fish_shellfish',
        ),
    ]
