# Generated by Django 4.2.6 on 2024-04-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekoption',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer'),
        ),
        migrations.AddField(
            model_name='weekoption',
            name='tuesday_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='weekoption',
            name='wednesday_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='option',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer'),
        ),
        migrations.AddField(
            model_name='option',
            name='week_option_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_one', to='nutrition.weekoption'),
        ),
        migrations.AddField(
            model_name='option',
            name='week_option_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_three', to='nutrition.weekoption'),
        ),
        migrations.AddField(
            model_name='option',
            name='week_option_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_two', to='nutrition.weekoption'),
        ),
        migrations.AddField(
            model_name='mealdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.dish'),
        ),
        migrations.AddField(
            model_name='mealdish',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(through='nutrition.MealDish', to='nutrition.dish'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.dish'),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(through='nutrition.DishIngredient', to='nutrition.ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='extras',
            field=models.ManyToManyField(related_name='extras', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='mid_morning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_morning', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack', to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='dayoption',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer'),
        ),
        migrations.AddField(
            model_name='dailydiet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.diet'),
        ),
        migrations.AddField(
            model_name='dailydiet',
            name='meals',
            field=models.ManyToManyField(to='nutrition.meal'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='friday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_friday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='monday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_monday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.option'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='saturday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_saturday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='sunday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sunday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='thursday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_thursday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='tuesday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tuesday_options', to='nutrition.dayoption'),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedoption',
            name='wednesday_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wednesday_options', to='nutrition.dayoption'),
        ),
        migrations.AlterUniqueTogether(
            name='mealdish',
            unique_together={('meal', 'dish')},
        ),
        migrations.AlterUniqueTogether(
            name='dailydiet',
            unique_together={('diet', 'date')},
        ),
    ]
