# Generated by Django 4.2.6 on 2024-02-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.dish')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal')),
            ],
            options={
                'unique_together': {('meal', 'dish')},
            },
        ),
        migrations.AlterField(
            model_name='meal',
            name='dishes',
            field=models.ManyToManyField(through='nutrition.MealDish', to='nutrition.dish'),
        ),
    ]
