# Generated by Django 4.2.6 on 2024-03-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='nutrition.meal')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='nutrition.meal')),
                ('extras', models.ManyToManyField(related_name='extras', to='nutrition.meal')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='nutrition.meal')),
                ('mid_morning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid_morning', to='nutrition.meal')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snack', to='nutrition.meal')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer')),
            ],
        ),
    ]
