# Generated by Django 3.2.1 on 2024-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20240201_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='unit_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
