# Generated by Django 4.2.6 on 2024-02-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_mealdish_alter_meal_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
    ]
