# Generated by Django 4.2.6 on 2024-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedoption',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
