# Generated by Django 4.2.6 on 2024-03-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('nutrition', '0003_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='DayOption',
        ),
    ]
