# Generated by Django 4.2.6 on 2024-03-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('nutrition', '0004_rename_option_dayoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_options', to='nutrition.dayoption')),
                ('monday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday_options', to='nutrition.dayoption')),
                ('saturday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday_options', to='nutrition.dayoption')),
                ('sunday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_options', to='nutrition.dayoption')),
                ('thursday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday_options', to='nutrition.dayoption')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer')),
                ('tuesday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_options', to='nutrition.dayoption')),
                ('wednesday_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_options', to='nutrition.dayoption')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.trainer')),
                ('week_option_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_one', to='nutrition.weekoption')),
                ('week_option_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_three', to='nutrition.weekoption')),
                ('week_option_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_option_two', to='nutrition.weekoption')),
            ],
        ),
    ]
