# Generated by Django 4.2.6 on 2024-03-20 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('nutrition', '0005_weekoption_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.regularuser')),
            ],
        ),
    ]
