# Generated by Django 4.2.6 on 2024-04-25 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FUERZA', 'Fuerza'), ('RESISTENCIA', 'Resistencia'), ('FLEXIBILIDAD', 'Flexibilidad'), ('CARDIO', 'Cardio'), ('HIIT', 'HIIT'), ('FUNCIONAL', 'Funcional'), ('BALANCE', 'Balance')], max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(through='sport.TrainingExercise', to='sport.exercise'),
        ),
    ]
