# Generated by Django 4.2.6 on 2024-01-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='food',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyDiet',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
