# Generated by Django 4.2.6 on 2024-02-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='user.trainer'),
        ),
    ]
