# Generated by Django 4.2.6 on 2024-06-11 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('friday', models.ManyToManyField(related_name='friday_trainings', to='sport.training')),
                ('monday', models.ManyToManyField(related_name='monday_trainings', to='sport.training')),
                ('saturday', models.ManyToManyField(related_name='saturday_trainings', to='sport.training')),
                ('sunday', models.ManyToManyField(related_name='sunday_trainings', to='sport.training')),
                ('thursday', models.ManyToManyField(related_name='thursday_trainings', to='sport.training')),
                ('tuesday', models.ManyToManyField(related_name='tuesday_trainings', to='sport.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wednesday', models.ManyToManyField(related_name='wednesday_trainings', to='sport.training')),
            ],
        ),
    ]
