# Generated by Django 4.2.6 on 2024-06-12 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0004_alter_weektraining_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weektraining',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='weektraining',
            name='user',
        ),
        migrations.AddField(
            model_name='weektraining',
            name='name',
            field=models.CharField(default='train', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AssignedWeekTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.weektraining')),
            ],
        ),
    ]
