# Generated by Django 3.2.1 on 2023-08-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20230809_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrecord',
            name='distance',
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='activity_type',
            field=models.CharField(choices=[('Caminar', 'Caminar'), ('Correr', 'Correr'), ('Nadar', 'Nadar'), ('Bicicleta', 'Bicicleta'), ('Ejercicio en casa', 'Ejercicio en casa'), ('Ejercicio en gimnasio', 'Ejercicio en gimnasio'), ('Otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='calorie_intake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_water_intake',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='diet_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Perder peso', 'Perder peso'), ('Ganar masa muscular', 'Ganar masa muscular'), ('Mantenerse en forma', 'Mantenerse en forma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hip_measurement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lifestyle',
            field=models.CharField(choices=[('Sedentario', 'Sedentario'), ('Ligero', 'Ligero'), ('Moderado', 'Moderado'), ('Activo', 'Activo'), ('Muy activo', 'Muy activo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='waist_measurement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='timer',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
