# Generated by Django 3.2.1 on 2023-08-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20230809_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('entrenador', 'Entrenador')], default='entrenador', max_length=20),
        ),
    ]
