# Generated by Django 4.2.4 on 2023-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('entrenador', 'Entrenador')], default='cliente', max_length=20),
        ),
    ]
