# Generated by Django 3.2.1 on 2023-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_customuser_age_alter_customuser_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('Perder peso', 'Perder peso'), ('Ganar masa muscular', 'Ganar masa muscular'), ('Mantenerse en forma', 'Mantenerse en forma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lifestyle',
            field=models.CharField(choices=[('Sedentario', 'Sedentario'), ('Ligero', 'Ligero'), ('Moderado', 'Moderado'), ('Activo', 'Activo'), ('Muy activo', 'Muy activo')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
