# Generated by Django 3.2.1 on 2023-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20230901_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(blank=True, choices=[('Perder peso', 'Perder peso'), ('Ganar masa muscular', 'Ganar masa muscular'), ('Mantenerse en forma', 'Mantenerse en forma')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('Sedentario', 'Sedentario'), ('Ligero', 'Ligero'), ('Moderado', 'Moderado'), ('Activo', 'Activo'), ('Muy activo', 'Muy activo')], max_length=50, null=True),
        ),
    ]
