# Generated by Django 3.2.1 on 2023-09-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20230901_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle_groups',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='timer',
        ),
    ]
