# Generated by Django 3.2.1 on 2023-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20230903_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainingexercise',
            name='repetitions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainingexercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
    ]
