# Generated by Django 3.2.1 on 2023-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20230904_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, through='application.TrainingExercise', to='application.Exercise'),
        ),
    ]
