# Generated by Django 3.2.1 on 2023-09-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_training_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(through='application.TrainingExercise', to='application.Exercise'),
        ),
    ]
