# Generated by Django 3.2.1 on 2023-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_training_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('proteina', models.FloatField(blank=True, null=True)),
                ('hc', models.FloatField(blank=True, null=True)),
                ('azucar', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('grasa', models.FloatField(blank=True, null=True)),
                ('grasa_sat', models.FloatField(blank=True, null=True)),
                ('apto_celiacos', models.BooleanField(blank=True, null=True)),
                ('apto_lactosa', models.BooleanField(blank=True, null=True)),
                ('apto_veganos', models.BooleanField(blank=True, null=True)),
                ('apto_vegetarianos', models.BooleanField(blank=True, null=True)),
                ('apto_pescetarianos', models.BooleanField(blank=True, null=True)),
                ('carne', models.BooleanField(blank=True, null=True)),
                ('verdura', models.BooleanField(blank=True, null=True)),
                ('pescado_marisco_enlatado_conserva', models.BooleanField(blank=True, null=True)),
                ('cereal', models.BooleanField(blank=True, null=True)),
                ('pasta_arroz', models.BooleanField(blank=True, null=True)),
                ('lacteo_yogur_queso', models.BooleanField(blank=True, null=True)),
                ('fruta', models.BooleanField(blank=True, null=True)),
                ('fruto_seco', models.BooleanField(blank=True, null=True)),
                ('legumbre', models.BooleanField(blank=True, null=True)),
                ('salsa_condimento', models.BooleanField(blank=True, null=True)),
                ('fiambre', models.BooleanField(blank=True, null=True)),
                ('pan_panMolde_tostada', models.BooleanField(blank=True, null=True)),
                ('huevo', models.BooleanField(blank=True, null=True)),
                ('suplemento_bebida_especial', models.BooleanField(blank=True, null=True)),
                ('tuberculo', models.BooleanField(blank=True, null=True)),
                ('otros', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
