# Generated by Django 3.2.1 on 2023-09-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='apto_celiacos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='apto_lactosa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='apto_pescetarianos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='apto_veganos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='apto_vegetarianos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cereal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fiambre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fruta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fruto_seco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='huevo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='lacteo_yogur_queso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='legumbre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='otros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='pan_panMolde_tostada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='pasta_arroz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='pescado_marisco_enlatado_conserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='salsa_condimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='suplemento_bebida_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='tuberculo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='verdura',
            field=models.BooleanField(default=False),
        ),
    ]
