# Generated by Django 3.2.1 on 2023-09-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20230906_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='cantidad',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('proteina', models.FloatField(blank=True, null=True)),
                ('hc', models.FloatField(blank=True, null=True)),
                ('azucar', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('grasa', models.FloatField(blank=True, null=True)),
                ('grasa_sat', models.FloatField(blank=True, null=True)),
                ('apto_celiacos', models.BooleanField(default=False)),
                ('apto_lactosa', models.BooleanField(default=False)),
                ('apto_veganos', models.BooleanField(default=False)),
                ('apto_vegetarianos', models.BooleanField(default=False)),
                ('apto_pescetarianos', models.BooleanField(default=False)),
                ('carne', models.BooleanField(default=False)),
                ('verdura', models.BooleanField(default=False)),
                ('pescado_marisco_enlatado_conserva', models.BooleanField(default=False)),
                ('cereal', models.BooleanField(default=False)),
                ('pasta_arroz', models.BooleanField(default=False)),
                ('lacteo_yogur_queso', models.BooleanField(default=False)),
                ('fruta', models.BooleanField(default=False)),
                ('fruto_seco', models.BooleanField(default=False)),
                ('legumbre', models.BooleanField(default=False)),
                ('salsa_condimento', models.BooleanField(default=False)),
                ('fiambre', models.BooleanField(default=False)),
                ('pan_panMolde_tostada', models.BooleanField(default=False)),
                ('huevo', models.BooleanField(default=False)),
                ('suplemento_bebida_especial', models.BooleanField(default=False)),
                ('tuberculo', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('alimentos', models.ManyToManyField(to='application.Alimento')),
            ],
        ),
    ]
