# Generated by Django 3.2.1 on 2023-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20230908_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='azucar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='cantidad',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fibra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasa_sat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='hc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteina',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='azucar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='fibra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='grasa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='grasa_sat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='hc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comida',
            name='proteina',
            field=models.FloatField(default=0),
        ),
    ]
