# Generated by Django 3.2.1 on 2023-09-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20230908_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDeDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('proteina', models.FloatField(blank=True, null=True)),
                ('hc', models.FloatField(blank=True, null=True)),
                ('azucar', models.FloatField(blank=True, null=True)),
                ('fibra', models.FloatField(blank=True, null=True)),
                ('grasa', models.FloatField(blank=True, null=True)),
                ('grasa_sat', models.FloatField(blank=True, null=True)),
                ('apto_celiacos', models.BooleanField(default=False)),
                ('apto_lactosa', models.BooleanField(default=False)),
                ('apto_veganos', models.BooleanField(default=False)),
                ('apto_vegetarianos', models.BooleanField(default=False)),
                ('apto_pescetarianos', models.BooleanField(default=False)),
                ('carne', models.BooleanField(default=False)),
                ('verdura', models.BooleanField(default=False)),
                ('pescado_marisco_enlatado_conserva', models.BooleanField(default=False)),
                ('cereal', models.BooleanField(default=False)),
                ('pasta_arroz', models.BooleanField(default=False)),
                ('lacteo_yogur_queso', models.BooleanField(default=False)),
                ('fruta', models.BooleanField(default=False)),
                ('fruto_seco', models.BooleanField(default=False)),
                ('legumbre', models.BooleanField(default=False)),
                ('salsa_condimento', models.BooleanField(default=False)),
                ('fiambre', models.BooleanField(default=False)),
                ('pan_panMolde_tostada', models.BooleanField(default=False)),
                ('huevo', models.BooleanField(default=False)),
                ('suplemento_bebida_especial', models.BooleanField(default=False)),
                ('tuberculo', models.BooleanField(default=False)),
                ('otros', models.BooleanField(default=False)),
                ('almuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='almuerzo', to='application.comida')),
                ('cena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cena', to='application.comida')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dias_de_dieta', to=settings.AUTH_USER_MODEL)),
                ('comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comida', to='application.comida')),
                ('desayuno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desayuno', to='application.comida')),
                ('merienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merienda', to='application.comida')),
            ],
        ),
    ]
