# Generated by Django 3.2.1 on 2023-09-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_dieta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDiaDeDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('dia_de_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.diadedieta')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.dieta')),
            ],
        ),
        migrations.AddField(
            model_name='dieta',
            name='dias_de_dieta',
            field=models.ManyToManyField(related_name='dietas', through='application.AsignacionDiaDeDieta', to='application.DiaDeDieta'),
        ),
    ]
