# Generated by Django 3.2.1 on 2023-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20230913_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimento',
            old_name='pescado_marisco_enlatado_conserva',
            new_name='enlatado_conserva',
        ),
        migrations.RenameField(
            model_name='comida',
            old_name='pescado_marisco_enlatado_conserva',
            new_name='enlatado_conserva',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='pescado_marisco_enlatado_conserva',
            new_name='enlatado_conserva',
        ),
        migrations.AddField(
            model_name='alimento',
            name='pescado_marisco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comida',
            name='pescado_marisco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pescado_marisco',
            field=models.BooleanField(default=False),
        ),
    ]
