# Generated by Django 3.2.1 on 2023-09-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20230913_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion1', to='application.opcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion2', to='application.opcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion3', to='application.opcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='suplementos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
