# Generated by Django 3.2.1 on 2023-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20230913_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='opcion1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='opcion2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='opcion3',
        ),
        migrations.AddField(
            model_name='plan',
            name='opciones',
            field=models.ManyToManyField(related_name='planes', to='application.Opcion'),
        ),
    ]
