# Generated by Django 3.2.1 on 2023-09-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20230914_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='opciones',
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion1', to='application.opcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion2', to='application.opcion'),
        ),
        migrations.AddField(
            model_name='plan',
            name='opcion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion3', to='application.opcion'),
        ),
    ]
