# Generated by Django 3.2.1 on 2023-09-19 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to=settings.AUTH_USER_MODEL),
        ),
    ]
