# Generated by Django 3.2.1 on 2023-09-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_calendario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='application.customuser'),
        ),
    ]
