# Generated by Django 4.2.4 on 2023-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_trainingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_issues',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_goals',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
