# Generated by Django 4.2.4 on 2023-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_alter_customuser_health_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='health_issues',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
