# Generated by Django 4.2.6 on 2023-10-20 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_alter_customuser_other_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.comidabase')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('almuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_almuerzo', to='application.comidavariable')),
                ('cena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_cena', to='application.comidavariable')),
                ('comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_comida', to='application.comidavariable')),
                ('desayuno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_desayuno', to='application.comidavariable')),
                ('merienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_merienda', to='application.comidavariable')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_almuerzo', to='application.comidavariable')),
                ('cena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_cena', to='application.comidavariable')),
                ('comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_comida', to='application.comidavariable')),
                ('desayuno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_desayuno', to='application.comidavariable')),
                ('merienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_merienda', to='application.comidavariable')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.opcionbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlanBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('suplementos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('opcion1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_opcion1', to='application.opcionvariable')),
                ('opcion2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_opcion2', to='application.opcionvariable')),
                ('opcion3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_opcion3', to='application.opcionvariable')),
            ],
        ),
        migrations.CreateModel(
            name='PlanVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('suplementos', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL)),
                ('opcion1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_opcion1', to='application.opcionvariable')),
                ('opcion2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_opcion2', to='application.opcionvariable')),
                ('opcion3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_opcion3', to='application.opcionvariable')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.planbase')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alimentos', models.ManyToManyField(to='application.alimentovariable')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentos_variables', models.ManyToManyField(to='application.alimentovariable')),
                ('plato_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.platobase')),
            ],
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='desayuno',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='merienda',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='opcion1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='opcion2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='opcion3',
        ),
        migrations.RenameModel(
            old_name='Alimento',
            new_name='AlimentoBase',
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
        migrations.AddField(
            model_name='comidavariable',
            name='platos_variables',
            field=models.ManyToManyField(to='application.platovariable'),
        ),
        migrations.AddField(
            model_name='comidabase',
            name='platos',
            field=models.ManyToManyField(to='application.platovariable'),
        ),
        migrations.AddField(
            model_name='alimentovariable',
            name='alimento_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.alimentobase'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.opcionvariable'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='application.planvariable'),
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
